import type { AdminApiClient } from "./client";

export type App = { id: string; name: string; callback_url?: string; delivery_mode: "queue" | "websocket" | "callback" | "all"; enabled: boolean; created_at: string; updated_at: string };
export type Credentials = { app_id: string; api_key: string; hmac_secret: string };
export type RoutingRule = { id: string; source_app_id?: string; event_type: string; target_app_id: string; realtime_channel?: string; enabled: boolean; created_at: string; updated_at: string };
export type AppInput = { name: string; delivery_mode: App["delivery_mode"]; callback_url?: string | null };
export type RuleInput = { source_app_id?: string | null; event_type: string; target_app_id: string; realtime_channel?: string | null; enabled?: boolean };
export type RealtimeConnection = { app_id: string; client_id: string; connection_id: string; instance_id: string; protocol: string; channels: string[]; connected_at: string; last_seen_at: string };
export type QueueSubscription = { id: string; app_id: string; name: string; enabled: boolean; paused_at?: string; draining_at?: string; drained_at?: string; max_in_flight: number; max_batch_size: number; ordering_mode: "none" | "key"; max_dispatch_rate?: number; success_callback_url?: string; failure_callback_url?: string; policy_version: number };
export type QueueSchedule = { id: string; name: string; enabled: boolean; cron_expression: string; timezone: string; event_type: string; next_run_at: string; last_run_at?: string };
export type QueueDepth = { available: number; in_flight: number; acknowledged: number; dead_letter: number; oldest_available_at?: string };
export type QueueCallbackOutcome = { id: string; delivery_id: string; event_id: string; generation: number; outcome: string; status: string; attempts: number; reason?: string; updated_at: string };

export const listApps = (client: AdminApiClient, signal?: AbortSignal) => client.request<App[]>("/api/v1/apps", { signal });
export const createApp = (client: AdminApiClient, input: AppInput) => client.request<Credentials>("/api/v1/apps", { method: "POST", body: input });
export const updateApp = (client: AdminApiClient, id: string, input: Partial<AppInput>) => client.request<App>(`/api/v1/admin/apps/${encodeURIComponent(id)}`, { method: "PATCH", body: input });
export const disableApp = (client: AdminApiClient, id: string) => client.request<App>(`/api/v1/apps/${encodeURIComponent(id)}`, { method: "DELETE" });
export const rotateApp = (client: AdminApiClient, id: string) => client.request<Credentials>(`/api/v1/apps/${encodeURIComponent(id)}/rotate-secret`, { method: "POST" });
export const listRules = (client: AdminApiClient, signal?: AbortSignal) => client.request<RoutingRule[]>("/api/v1/routing/rules", { signal });
export const createRule = (client: AdminApiClient, input: RuleInput) => client.request<RoutingRule>("/api/v1/routing/rules", { method: "POST", body: input });
export const updateRule = (client: AdminApiClient, id: string, input: Partial<RuleInput>) => client.request<RoutingRule>(`/api/v1/routing/rules/${encodeURIComponent(id)}`, { method: "PATCH", body: input });
export const deleteRule = (client: AdminApiClient, id: string) => client.request(`/api/v1/routing/rules/${encodeURIComponent(id)}`, { method: "DELETE" });
export const studioToken = (client: AdminApiClient, appID: string, protocol: "realtime_v2" | "realtime" | "stream", clientID = "studio", channels: string[] = []) => client.request<{ token: string; expires_at: string }>("/api/v1/admin/studio/token", { method: "POST", body: { app_id: appID, protocol, ...(protocol === "realtime_v2" ? { client_id: clientID, channels } : {}) } });
export const studioPublish = (client: AdminApiClient, appID: string, channel: string, data: Record<string, unknown>) => client.request("/api/v1/admin/studio/publish", { method: "POST", body: { app_id: appID, channel, data } });
export const listConnections = (client: AdminApiClient, appID: string, signal?: AbortSignal) => client.request<{ connections: RealtimeConnection[] }>(`/api/v1/admin/connections?app_id=${encodeURIComponent(appID)}&limit=100`, { signal });
export const disconnectConnection = (client: AdminApiClient, appID: string, connectionID: string) => client.request(`/api/v1/admin/connections/${encodeURIComponent(connectionID)}?app_id=${encodeURIComponent(appID)}`, { method: "DELETE" });
const adminQueuePath = (appID: string, subscriptionID = "") => `/api/v1/admin/apps/${encodeURIComponent(appID)}/subscriptions${subscriptionID ? `/${encodeURIComponent(subscriptionID)}` : ""}`;
export const listAdminSubscriptions = (client: AdminApiClient, appID: string, signal?: AbortSignal) => client.request<{items: QueueSubscription[]}>(adminQueuePath(appID), {signal});
export const getAdminQueueDepth = (client: AdminApiClient, appID: string, subscriptionID: string, signal?: AbortSignal) => client.request<QueueDepth>(`${adminQueuePath(appID, subscriptionID)}/metrics`, {signal});
export const listAdminQueueSchedules = (client: AdminApiClient, appID: string, subscriptionID: string, signal?: AbortSignal) => client.request<{items: QueueSchedule[]}>(`${adminQueuePath(appID, subscriptionID)}/schedules`, {signal});
export const listAdminQueueCallbacks = (client: AdminApiClient, appID: string, subscriptionID: string, signal?: AbortSignal) => client.request<{items: QueueCallbackOutcome[]}>(`${adminQueuePath(appID, subscriptionID)}/callbacks`, {signal});
export const drainAdminQueue = (client: AdminApiClient, appID: string, subscriptionID: string, timeoutSeconds = 30) => client.request(`${adminQueuePath(appID, subscriptionID)}/drain`, {method: "POST", body: {timeout_seconds: timeoutSeconds}});
