# Example: replace `backend_app` with your upstream server name and port
# If using Docker compose above, backend service name is `api`.

upstream backend_app {
  # TODO: replace host/port to your backend target
  server api:8080;
}

server {
  listen 80;

  # /docs static
  location = /docs {
    return 302 /docs/;
  }

  location ^~ /docs/ {
    root /srv/docs/public-docs;
    index index.html;
    # SPA/fallback for static markdown pages under /docs/ and index
    try_files $uri $uri/ /index.html;
  }

  location / {
    proxy_pass http://backend_app;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
