import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { useAuth } from "../auth/AuthProvider";
import { AsyncState } from "../components/AsyncState";
import { drainAdminQueue, getAdminQueueDepth, listAdminQueueCallbacks, listAdminQueueSchedules, listAdminSubscriptions, listApps } from "../api/controlPlane";

export function QueuePage() {
  const {client} = useAuth(); const queryClient = useQueryClient(); const [appID,setAppID] = useState(""); const [subscriptionID,setSubscriptionID] = useState("");
  const apps = useQuery({queryKey:["admin-apps"],queryFn:({signal})=>listApps(client,signal)});
  const subscriptions = useQuery({queryKey:["queue-subscriptions",appID],queryFn:({signal})=>listAdminSubscriptions(client,appID,signal),enabled:Boolean(appID),refetchInterval:10_000});
  useEffect(()=>{ if (!subscriptions.data?.items.some(item=>item.id===subscriptionID)) setSubscriptionID(subscriptions.data?.items[0]?.id ?? ""); },[subscriptions.data,subscriptionID]);
  const enabled = Boolean(appID&&subscriptionID); const depth = useQuery({queryKey:["queue-depth",appID,subscriptionID],queryFn:({signal})=>getAdminQueueDepth(client,appID,subscriptionID,signal),enabled,refetchInterval:5_000});
  const schedules = useQuery({queryKey:["queue-schedules",appID,subscriptionID],queryFn:({signal})=>listAdminQueueSchedules(client,appID,subscriptionID,signal),enabled,refetchInterval:10_000});
  const callbacks = useQuery({queryKey:["queue-callbacks",appID,subscriptionID],queryFn:({signal})=>listAdminQueueCallbacks(client,appID,subscriptionID,signal),enabled,refetchInterval:5_000});
  const drain = useMutation({mutationFn:()=>drainAdminQueue(client,appID,subscriptionID),onSuccess:()=>void queryClient.invalidateQueries({queryKey:["queue-subscriptions",appID]})});
  const selected = subscriptions.data?.items.find(item=>item.id===subscriptionID);
  return <main className="page" id="main-content"><p className="eyebrow">DURABLE PULL OPERATIONS</p><h1 tabIndex={-1}>Queue v2</h1><p className="page-lede">Inspect subscription policy, bounded depth, recurring schedules, priority aging and generation-fenced result callbacks.</p>
    <section className="studio-controls"><label>Application<select value={appID} onChange={event=>{setAppID(event.target.value);setSubscriptionID("");}}><option value="">Select app</option>{apps.data?.filter(app=>app.enabled).map(app=><option key={app.id} value={app.id}>{app.name}</option>)}</select></label><label>Subscription<select value={subscriptionID} onChange={event=>setSubscriptionID(event.target.value)} disabled={!appID}><option value="">Select subscription</option>{subscriptions.data?.items.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="danger-button" disabled={!enabled||Boolean(selected?.draining_at)||drain.isPending} onClick={()=>drain.mutate()}>Drain subscription</button></section>
    {subscriptions.isError&&<AsyncState title="Queue unavailable" role="alert">{subscriptions.error.message}</AsyncState>}
    {selected&&<section className="detail-grid"><article><h2>Policy</h2><dl><dt>Status</dt><dd>{selected.drained_at?"Drained":selected.draining_at?"Draining":selected.paused_at?"Paused":"Active"}</dd><dt>Ordering</dt><dd>{selected.ordering_mode}</dd><dt>In-flight cap</dt><dd>{selected.max_in_flight}</dd><dt>Batch cap</dt><dd>{selected.max_batch_size}</dd><dt>Fairness</dt><dd>Priority ages one class/minute to a bounded maximum.</dd></dl></article><article><h2>Depth</h2><dl><dt>Available</dt><dd>{depth.data?.available ?? "—"}</dd><dt>In flight</dt><dd>{depth.data?.in_flight ?? "—"}</dd><dt>Acknowledged</dt><dd>{depth.data?.acknowledged ?? "—"}</dd><dt>Dead letter</dt><dd>{depth.data?.dead_letter ?? "—"}</dd></dl></article></section>}
    {enabled&&<><div className="table-wrap"><table><caption>Recurring schedules</caption><thead><tr><th>Name</th><th>Cron</th><th>Timezone</th><th>Event</th><th>Next run</th><th>Status</th></tr></thead><tbody>{schedules.data?.items.map(item=><tr key={item.id}><td>{item.name}</td><td><code>{item.cron_expression}</code></td><td>{item.timezone}</td><td><code>{item.event_type}</code></td><td>{new Date(item.next_run_at).toLocaleString()}</td><td>{item.enabled?"Enabled":"Disabled"}</td></tr>)}</tbody></table></div><div className="table-wrap"><table><caption>Result callback outcomes</caption><thead><tr><th>Delivery</th><th>Outcome</th><th>Status</th><th>Attempts</th><th>Reason</th></tr></thead><tbody>{callbacks.data?.items.map(item=><tr key={item.id}><td><code>{item.delivery_id}</code></td><td>{item.outcome}</td><td>{item.status}</td><td>{item.attempts}</td><td>{item.reason??"—"}</td></tr>)}</tbody></table></div></>}
  </main>;
}
