import { useQuery } from "@tanstack/react-query";
import { useEffect, useRef, useState } from "react";
import { listApps, studioPublish, studioToken } from "../api/controlPlane";
import { useAuth } from "../auth/AuthProvider";

type FrameLog = { id: number; at: string; direction: "in" | "out" | "system"; frame: string };
export function RealtimeStudioPage() {
  const { client } = useAuth(); const apps = useQuery({ queryKey: ["admin-apps"], queryFn: ({ signal }) => listApps(client, signal) }); const socket = useRef<WebSocket>(); const sequence = useRef(0); const [appID, setAppID] = useState(""); const [protocol, setProtocol] = useState<"realtime" | "stream">("realtime"); const [state, setState] = useState("Disconnected"); const [logs, setLogs] = useState<FrameLog[]>([]); const [paused, setPaused] = useState(false); const [filter, setFilter] = useState("");
  const append = (direction: FrameLog["direction"], frame: string) => { if (!paused) setLogs((current) => [...current.slice(-499), { id: ++sequence.current, at: new Date().toISOString(), direction, frame: redactFrame(frame) }]); };
  const close = () => { socket.current?.close(1000, "operator close"); socket.current = undefined; setState("Disconnected"); };
  useEffect(() => close, []);
  const connect = async () => { close(); if (!appID) return; setState("Connecting"); try { const issued = await studioToken(client, appID, protocol); const scheme = location.protocol === "https:" ? "wss" : "ws"; const path = protocol === "stream" ? "/api/v1/stream" : "/ws"; const ws = new WebSocket(`${scheme}://${location.host}${path}?token=${encodeURIComponent(issued.token)}`); socket.current = ws; ws.onopen = () => { setState("Connected"); append("system", `${protocol} connected`); }; ws.onmessage = (event) => append("in", String(event.data)); ws.onerror = () => append("system", "WebSocket transport error"); ws.onclose = (event) => { setState("Disconnected"); append("system", `closed ${event.code}`); }; } catch (error) { setState("Disconnected"); append("system", error instanceof Error ? error.message : "Connection failed"); } };
  const send = (frame: string) => { if (socket.current?.readyState !== WebSocket.OPEN) return; socket.current.send(frame); append("out", frame); };
  const visible = logs.filter((entry) => !filter || `${entry.direction} ${entry.frame}`.toLowerCase().includes(filter.toLowerCase()));
  return <main className="page" id="main-content"><p className="eyebrow">INTERACTIVE TOOLS</p><h1 tabIndex={-1}>Realtime Studio</h1><p className="page-lede">Exercise standard realtime and durable stream sockets with five-minute app-scoped tokens. Tokens never enter the frame log.</p><section className="studio-controls"><label>Application<select value={appID} onChange={(event) => setAppID(event.target.value)}><option value="">Select app</option>{apps.data?.filter((app) => app.enabled).map((app) => <option key={app.id} value={app.id}>{app.name}</option>)}</select></label><label>Protocol<select value={protocol} onChange={(event) => setProtocol(event.target.value as typeof protocol)}><option value="realtime">Realtime v1</option><option value="stream">Durable stream</option></select></label><div><span className="connection-state">{state}</span>{state === "Connected" ? <button className="quiet-button" onClick={close}>Close</button> : <button className="primary-button" disabled={!appID} onClick={connect}>Connect</button>}</div></section>
    <StudioComposer protocol={protocol} disabled={state !== "Connected"} send={send} publish={(channel, data) => studioPublish(client, appID, channel, data).then(() => append("out", JSON.stringify({ type: "channel.publish", channel, data })))} />
    <section className="studio-log"><div className="studio-log-toolbar"><h2>Frame log</h2><label>Filter<input value={filter} onChange={(event) => setFilter(event.target.value)} /></label><button className="quiet-button" onClick={() => setPaused((value) => !value)}>{paused ? "Resume" : "Pause"}</button><button className="quiet-button" onClick={() => setLogs([])}>Clear</button><button className="quiet-button" onClick={() => downloadLogs(visible)}>Export redacted</button></div><ol>{visible.map((entry) => <li key={entry.id}><time>{entry.at}</time><span>{entry.direction}</span><pre>{entry.frame}</pre></li>)}</ol></section>
  </main>;
}
function StudioComposer({ protocol, disabled, send, publish }: { protocol: "realtime" | "stream"; disabled: boolean; send(frame: string): void; publish(channel: string, data: Record<string, unknown>): Promise<void> }) { const [topics, setTopics] = useState("events,jobs"); const [channel, setChannel] = useState("studio.test"); const [data, setData] = useState('{"hello":"relayhub"}'); return <section className="studio-composer"><h2>Actions</h2>{protocol === "realtime" && <><label>Topics<input value={topics} onChange={(event) => setTopics(event.target.value)} /></label><button className="quiet-button" disabled={disabled} onClick={() => send(JSON.stringify({ type: "subscribe", topics: topics.split(",").map((value) => value.trim()).filter(Boolean) }))}>Subscribe</button><label>Channel<input value={channel} onChange={(event) => setChannel(event.target.value)} /></label><label>JSON data<textarea value={data} onChange={(event) => setData(event.target.value)} /></label><button className="quiet-button" disabled={disabled} onClick={() => { try { publish(channel, JSON.parse(data)); } catch { /* server/UI validation keeps malformed input local */ } }}>Publish</button></>}{protocol === "stream" && <button className="quiet-button" disabled={disabled} onClick={() => send(JSON.stringify({ type: "consumer.start", max_in_flight: 10 }))}>Start consumer</button>}</section>; }
function redactFrame(value: string) { return value.replace(/([?&]token=)[^&\s"]+/gi, "$1[REDACTED]").replace(/(Bearer\s+)[^\s"]+/gi, "$1[REDACTED]").slice(0, 65_536); }
function downloadLogs(logs: FrameLog[]) { const url = URL.createObjectURL(new Blob([JSON.stringify(logs, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = "relayhub-studio-redacted.json"; link.click(); URL.revokeObjectURL(url); }
