import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { createRule, deleteRule, listApps, listRules, updateRule, type RuleInput } from "../api/controlPlane";
import { useAuth } from "../auth/AuthProvider";
import { AsyncState } from "../components/AsyncState";

export function RoutingRulesPage() {
  const { client } = useAuth(); const cache = useQueryClient(); const rules = useQuery({ queryKey: ["admin-rules"], queryFn: ({ signal }) => listRules(client, signal) }); const apps = useQuery({ queryKey: ["admin-apps"], queryFn: ({ signal }) => listApps(client, signal) }); const refresh = () => cache.invalidateQueries({ queryKey: ["admin-rules"] });
  const create = useMutation({ mutationFn: (input: RuleInput) => createRule(client, input), onSuccess: refresh }); const toggle = useMutation({ mutationFn: ({ id, enabled }: { id: string; enabled: boolean }) => updateRule(client, id, { enabled }), onSuccess: refresh }); const remove = useMutation({ mutationFn: (id: string) => deleteRule(client, id), onSuccess: refresh });
  return <main className="page" id="main-content"><p className="eyebrow">CONTROL PLANE</p><h1 tabIndex={-1}>Routing Rules</h1><p className="page-lede">Route matching event types to enabled target applications and optional realtime channels.</p>
    <form className="control-form" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const source = String(data.get("source_app_id") || ""); const channel = String(data.get("realtime_channel") || "").trim(); create.mutate({ source_app_id: source || null, event_type: String(data.get("event_type") || "").trim(), target_app_id: String(data.get("target_app_id") || ""), realtime_channel: channel || null }); }}><h2>Create rule</h2><label>Source app<select name="source_app_id"><option value="">Any source</option>{apps.data?.filter((app) => app.enabled).map((app) => <option key={app.id} value={app.id}>{app.name}</option>)}</select></label><label>Event type<input name="event_type" required /></label><label>Target app<select name="target_app_id" required><option value="">Select target</option>{apps.data?.filter((app) => app.enabled).map((app) => <option key={app.id} value={app.id}>{app.name}</option>)}</select></label><label>Realtime channel<input name="realtime_channel" pattern="[a-z0-9][a-z0-9_.:-]{0,95}" /></label><button className="primary-button" disabled={create.isPending}>Create rule</button></form>
    {create.error && <p className="form-error">{create.error.message}</p>}{rules.isPending && <AsyncState title="Loading rules">Reading routing rules…</AsyncState>}{rules.isError && <AsyncState title="Rules unavailable" role="alert">{rules.error.message}</AsyncState>}{rules.data && <div className="table-wrap"><table><caption>Routing rules</caption><thead><tr><th>Event</th><th>Source</th><th>Target</th><th>Channel</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rules.data.map((rule) => <tr key={rule.id}><td>{rule.event_type}</td><td><code>{rule.source_app_id ?? "*"}</code></td><td><code>{rule.target_app_id}</code></td><td>{rule.realtime_channel ?? "—"}</td><td>{rule.enabled ? "Enabled" : "Paused"}</td><td className="action-cell"><button className="quiet-button" onClick={() => toggle.mutate({ id: rule.id, enabled: !rule.enabled })}>{rule.enabled ? "Pause" : "Enable"}</button><button className="quiet-button" onClick={() => remove.mutate(rule.id)}>Delete</button></td></tr>)}</tbody></table></div>}
  </main>;
}
