package web

//go:generate sh ../scripts/build-skill.sh
//go:generate sh ../scripts/build-llms.sh
//go:generate go run ./cmd/gendocs -source ../../web/admin/dist -output embed.go

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io/fs"
	"sort"
	"strings"
)

const maxAdminAssetBytes = 5 << 20

type manifestEntry struct {
	File    string   `json:"file"`
	CSS     []string `json:"css"`
	Assets  []string `json:"assets"`
	IsEntry bool     `json:"isEntry"`
}

func Generate(source fs.FS) ([]byte, error) {
	var names []string
	files := make(map[string][]byte)
	err := fs.WalkDir(source, ".", func(name string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return nil
		}
		if !fs.ValidPath(name) || entry.Type()&fs.ModeSymlink != 0 || strings.HasSuffix(name, ".map") {
			return fmt.Errorf("invalid Admin asset %q", name)
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		if info.Size() > maxAdminAssetBytes {
			return fmt.Errorf("Admin asset %q exceeds 5 MiB", name)
		}
		data, err := fs.ReadFile(source, name)
		if err != nil {
			return err
		}
		files[name] = data
		names = append(names, name)
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walk docs source: %w", err)
	}
	if err := validateAdminBuild(files); err != nil {
		return nil, err
	}
	sort.Strings(names)

	var generated bytes.Buffer
	generated.WriteString("// Code generated by go -C backend generate ./web; DO NOT EDIT.\n\n")
	generated.WriteString("package web\n\n")
	generated.WriteString("import (\n\t\"io/fs\"\n\t\"testing/fstest\"\n)\n\n")
	generated.WriteString("var Admin fs.FS = fstest.MapFS{\n")
	for _, name := range names {
		_, _ = fmt.Fprintf(&generated, "%q: {Data: []byte(%q)},\n", name, string(files[name]))
	}
	generated.WriteString("}\n")

	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format embedded docs source: %w", err)
	}
	return formatted, nil
}

func validateAdminBuild(files map[string][]byte) error {
	index, ok := files["index.html"]
	if !ok {
		return fmt.Errorf("Admin build is missing index.html")
	}
	if bytes.Contains(index, []byte("http://")) || bytes.Contains(index, []byte("https://")) {
		return fmt.Errorf("Admin index contains an external runtime URL")
	}
	rawManifest, ok := files[".vite/manifest.json"]
	if !ok {
		return fmt.Errorf("Admin build is missing Vite manifest")
	}
	var manifest map[string]manifestEntry
	if err := json.Unmarshal(rawManifest, &manifest); err != nil {
		return fmt.Errorf("decode Admin Vite manifest: %w", err)
	}
	entry, ok := manifest["index.html"]
	if !ok || !entry.IsEntry || entry.File == "" {
		return fmt.Errorf("Admin Vite manifest has no index entry")
	}
	for _, name := range append(append([]string{entry.File}, entry.CSS...), entry.Assets...) {
		if !fs.ValidPath(name) || files[name] == nil {
			return fmt.Errorf("Admin Vite manifest references missing asset %q", name)
		}
		if !bytes.Contains(index, []byte("/admin/"+name)) {
			return fmt.Errorf("Admin index does not reference manifest asset %q", name)
		}
	}
	return nil
}
