package web

//go:generate sh ../scripts/build-skill.sh
//go:generate sh ../scripts/build-llms.sh
//go:generate go run ./cmd/gendocs -source ../public-docs -output embed.go

import (
	"bytes"
	"fmt"
	"go/format"
	"io/fs"
	"sort"
)

func Generate(source fs.FS) ([]byte, error) {
	var names []string
	err := fs.WalkDir(source, ".", func(name string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if !entry.IsDir() {
			names = append(names, name)
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walk docs source: %w", err)
	}
	sort.Strings(names)

	var generated bytes.Buffer
	generated.WriteString("// Code generated by go generate ./web; DO NOT EDIT.\n\n")
	generated.WriteString("package web\n\n")
	generated.WriteString("import (\n\t\"io/fs\"\n\t\"testing/fstest\"\n)\n\n")
	generated.WriteString("var Public fs.FS = fstest.MapFS{\n")
	for _, name := range names {
		data, err := fs.ReadFile(source, name)
		if err != nil {
			return nil, fmt.Errorf("read docs source %q: %w", name, err)
		}
		_, _ = fmt.Fprintf(&generated, "%q: {Data: []byte(%q)},\n", name, string(data))
	}
	generated.WriteString("}\n")

	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format embedded docs source: %w", err)
	}
	return formatted, nil
}
